#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright (c) 2013-2025 The University of Manchester, UK.
#
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
#  * Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
#  * Neither the names of The University of Manchester nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Author: Robert Haines

require 'rubygems'
require 'bundler/setup'
require 'ucf'

def usage
  puts "Usage:\n  create-ucf <ucf-file>"
  exit 1
end

usage unless ARGV.length == 1

ucffile = ARGV[0]

if File.exist?(ucffile)
  puts "File '#{ucffile}' already exists. Exiting."
  exit 1
end

begin
  UCF::File.create(ucffile) do |c|
    # Add a cheery greeting file from a string.
    c.file.open('greeting.txt', 'w') do |f|
      f.puts 'Hello, World!'
    end

    # Create a subdirectory.
    c.dir.mkdir('dir')

    # Copy this example code in straight from a file.
    c.add('dir/code.rb', __FILE__)

    # Add a explanation of this file.
    c.comment = 'This is an example UCF file!'
  end
rescue ZipContainer::MalformedContainerError, ZipContainer::Error => e
  puts e
  exit 1
end
